apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application-api-gateway
  labels: 
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test  
  template:
    metadata:
      labels: 
        env: test
    spec:
      volumes:
       - name: config
         configMap:
          name:   application-api-gateway-config
      containers:
        - name:  application-api-gateway
          image: montud/application-api-gateway:latest
          volumeMounts:
            - name: config
              mountPath: "/config"
          env:
            - name: server.port
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: server.port
            - name: spring.application.name
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.application.name
            - name: spring.cloud.gateway.libraryadmin.route.id
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.libraryadmin.route.id
            - name: spring.cloud.gateway.libraryadmin.route.uri
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.libraryadmin.route.uri
            - name: spring.cloud.gateway.libraryadmin.route.predicates
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.libraryadmin.route.predicates
            - name: spring.cloud.gateway.bookcatalog.route.id
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.bookcatalog.route.id
            - name: spring.cloud.gateway.bookcatalog.route.uri
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.bookcatalog.route.uri
            - name: spring.cloud.gateway.bookcatalog.route.predicates
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.bookcatalog.route.predicates
            - name: spring.cloud.gateway.users.route.id
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.users.route.id
            - name: spring.cloud.gateway.users.route.uri
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.users.route.uri
            - name: spring.cloud.gateway.users.route.predicates
              valueFrom:  
                configMapKeyRef:
                  name: application-api-gateway-config
                  key: spring.cloud.gateway.users.route.predicates
          ports:
            - containerPort: 8085

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-api-gateway-config
data:
  server.port: "8085"
  spring.application.name: "api-gateway"
  spring.cloud.gateway.libraryadmin.route.id: "LIBRARYADMIN"
  spring.cloud.gateway.libraryadmin.route.uri: "lb://LIBRARYADMIN"
  spring.cloud.gateway.libraryadmin.route.predicates: "/api/admin/**"
  spring.cloud.gateway.bookcatalog.route.id: "BOOKCATALOG"
  spring.cloud.gateway.bookcatalog.route.uri: "lb://BOOKCATALOG"
  spring.cloud.gateway.bookcatalog.route.predicates: "/api/book/**"
  spring.cloud.gateway.users.route.id: "USERS"
  spring.cloud.gateway.users.route.uri: "lb://USERS"
  spring.cloud.gateway.users.route.predicates: "/api/user/**"

            

