apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application-api-gateway
  labels: 
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test  
  template:
    metadata:
      labels: 
        env: test
    spec:
      containers:
        - name:  application-api-gateway
          image: montud/application-api-gateway:latest
          ports:
            - containerPort: 8080
            

