apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application-api-gateway
  labels: 
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      env: test  
  template:
    metadata:
      labels: 
        env: test
    spec:
      containers:
        - name:  application-api-gateway
          image: montud/application-api-gateway:latest
          ports:
            - containerPort: 8080

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-api-gateway-config
data:
  server.port: "8085"
  spring.application.name: "api-gateway"
  spring.cloud.gateway.libraryadmin.route.id: "LIBRARYADMIN"
  spring.cloud.gateway.libraryadmin.route.uri: "lb://LIBRARYADMIN"
  spring.cloud.gateway.libraryadmin.route.predicates: "/api/admin/**"
  spring.cloud.gateway.bookcatalog.route.id: "BOOKCATALOG"
  spring.cloud.gateway.bookcatalog.route.uri: "lb://BOOKCATALOG"
  spring.cloud.gateway.bookcatalog.route.predicates: "/api/book/**"
  spring.cloud.gateway.users.route.id: "USERS"
  spring.cloud.gateway.users.route.uri: "lb://USERS"
  spring.cloud.gateway.users.route.predicates: "/api/user/**"

            

