server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: LIBRARYADMIN
          uri: lb://LIBRARYADMIN
          predicates:
          - Path=/api/admin/**
          
        - id: BOOKCATALOG
          uri: lb://BOOKCATALOG
          predicates:
          - Path=/api/book/**
          
        - id: BOOKCATALOG
          uri: lb://USERS
          predicates:
          - Path=/api/user/**
          
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true