server:
  port: ${server.port}

spring:
  application:
    name: ${spring.application.name}
  cloud:
    gateway:
      routes:
        - id: ${spring.cloud.gateway.libraryadmin.route.id}
          uri: ${spring.cloud.gateway.libraryadmin.route.uri}
          predicates:
          - Path=${spring.cloud.gateway.libraryadmin.route.predicates}
          
        - id: ${spring.cloud.gateway.bookcatalog.route.id}
          uri: ${spring.cloud.gateway.bookcatalog.route.uri}
          predicates:
          - Path=${spring.cloud.gateway.bookcatalog.route.predicates}
          
        - id: ${spring.cloud.gateway.users.route.id}
          uri: ${spring.cloud.gateway.users.route.uri}
          predicates:
          - Path=${spring.cloud.gateway.users.route.predicates}
          
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    service-url:
      defaultZone: http://microservice-discovery/eureka
    fetch-registry: true
    register-with-eureka: true